### PR TITLE
less horible

### PR DESCRIPTION
**Pull request by buthed010203**
Ew underscores in var names

### CODE REVIEW

**Comment by zxtej** [comment]
the code is such an embarrassment gonna just wipe it off this repo

**Comment by buthed010203** [comment]
What is the purpose of the custom script even anyways

**Comment by zxtej** [comment]
nothing

**Comment by zxtej** [comment]
was planning to do some random weird things with it but didnt know the actual project structure
but after spending 10 years staring at the thing think i know roughly how to implement

**Pull request closed without merging**
